#+title: Emacs Literate Startup
#+author: gynamics
#+date: <2026-07-21 Tue>
#+property: header-args :tangle yes

* Prelude
** preface
Principles of my Emacs configuration:

1. less is more: policy rather than framework
2. iterability: always ease to modify rather than contiguous integration
3. readability: representation determines control structure while interaction methods determine representation

By (1) and (2), I just separate configurations into code blocks and ~use-package~ statements. As for cross-block dependencies, they can be removed by
1. internal dependency serialization: adjust loading order with ~use-package~ keywords, hooks and other emacs utilities.
2. external dependency integration: push these variables forward with some helpers.
so that all packages can be loosely coupled. I just care about if a package can be joined or replaced with minimal affects, rather than if a package can be joined in the same manner. Even a heavy refactorization shouldn't bother the existing code unless there is a significant change in package management.

By (3), ~org-mode~ can organize everything for me. I do not need a sparse directory tree with annoying abstract levels, and I can edit this document as efficient as edit a project in an IDE, because lisp is good at process nested structures, and org document itself is a tree.

My main goal is to produce a portable configuration that can be easily ported to a new machine, and then keep iterating with it. If you believe that there will never be an ultimate Emacs configuration for you, then why not embrace this stinging world and enjoy a thorny road?

** header
More and more packages, more and more configuration code, it turns to be more and more inconvenient to browse them in a single ~init.el~. However, if we separate them into multiple files, it actually exacerbates the dilemma of loose configuration management.

Therefore we will need a method to organize that large configuration file, both conceptually and visually. Although this could be achieved by a variety of tools in Emacs IDE without bothering the code itself, a more powerful approach is to bring everything into an org document.

This configuration style make use of ~org-babel-load-file~, with ~org-mode~, we can slice these emacs configuration blocks into smaller and smaller code blocks with good document (and all kinds of other information related) attached, which are always well organized in a tree.

This is the header of generated file:

#+begin_src emacs-lisp
  ;;; koishimacs.el --- auto-generated configuration -*- lexical-binding: t -*-

  ;; Author: gynamics
  ;; Version: 6.0.1

  ;;; Commentary:

  ;; Koishimacs -- The Emacs in Your Subconsciousness
  ;; This file is auto-generated from org blocks.

  ;;; Code:

  ;; check if current Emacs version supports this configuration
  (when (< emacs-major-version 31)
    (error "This Emacs version is not supported!"))
#+end_src

You modifications in org code blocks will not take effect until next startup. If you want some options take effect immediately for further operations (e. g. set ~use-package-deferring-keywords~), you can evaluate them immediately with ~C-x C-e~ (~eval-last-sexp~).

** startup
Literate startup document needs to be tangled into a single ~.el~ or ~.elc~ file, because ~org-babel-tangle-file~ will take a little bit of time to tangle a series of blocks. You can then compile this file, but that doesn't matter performance.

BTW, most user-defined configuration interfaces has prefix ~my:~, and variables has prefix ~my/~. Just a personal naming style. Emacs Lisp does not support Common Lisp style modules, this naming style is rejected by ~package-lint~, but personal configuration is a terminal of packages, so let's be free here.

#+begin_src emacs-lisp
  (autoload #'org-babel-tangle-file "ob-tangle")

  (defun my:tangle-koishimacs:full (byte-compile-p)
    "Tangle all code blocks in koishimacs.org and write them to koishimacs.el .
  If BYTE-COMPILE-P is given as t, byte compile it."
    (interactive "P")
    (let ((source-file (concat user-emacs-directory "koishimacs.org"))
          (output-file (concat user-emacs-directory "koishimacs.el")))
      (org-babel-tangle-file source-file output-file)
      (when byte-compile-p
        (let ((byte-compile-warnings
               '(not free-vars unresolved noruntime lexical make-local)))
          (byte-compile-file output-file)))))
#+end_src

Early evaluation takes place in the compiling process, this will slightly reduce some work like patching and updating packages. If there happened to be something wrong with a code block, you can add ~:tangle no~ after ~#+begin_src emacs-lisp~ to skip it when compiling, then recompile the configuration file and debug that block manually on next startup.

** environment
There are several helpers help create or neglect missing files in initialization. A more generic implementation is expected here (e . g. add ~:depends~ or ~:import~ keywords to ~use-package~, but this seems to be unnecessary)

#+begin_src emacs-lisp
  (defun my:strong-directory (dir &optional parents)
    "Return DIR, if it does not exist, try to create it.
  If it is a relative path, create it under path PARENTS."
    (if (file-directory-p dir)
        dir
      (condition-case nil
          (make-directory dir parents)
        (:success dir)
        (error (error "Failed to create directory %s" dir)))))

  (defun my:weak-directory (dir)
    "Return DIR, if it does not exist return nil."
    (when (file-directory-p dir) dir))

  (defun my:weak-path (path)
    "Return PATH, if it does not exist return nil."
    (when (file-exists-p path) path))
#+end_src

~setenv~ will just set environment variable for current emacs process, in ~process-environment~.

However, if we start a subprocess from emacs, it uses environment variables inherited from the parent process of Emacs, which provides ~initial-environment~. To change this, we should modify variable ~exec-path~.

#+begin_src emacs-lisp
  (defun my:add-to-env-path (paths)
    "Add path strings in list PATHS to environment variable $PATH."
    (let ((env-path (split-string-and-unquote (getenv "PATH") ":")))
      (setenv "PATH" (mapconcat 'identity (append paths env-path) ":"))))

  (defun my:add-to-exec-path (paths)
    "Add path strings in list PATHS to list var EXEC-PATH."
    (setf exec-path (append paths exec-path)))

  (defun my:strip-list (&rest args)
    "Construct a list with ARGS, remove nils in ARGS."
    (mapcan (lambda (arg) (when arg (list arg))) args))

  (defun my:add-to-path (&rest paths)
    "Add path string PATHS to both $PATH and EXEC-PATH."
    (let ((l (apply #'my:strip-list paths)))
      (when l
        (my:add-to-env-path l)
        (my:add-to-exec-path l))))

  (let ((home (file-name-as-directory (getenv "HOME"))))
    ;; for some local tools, this should be added to PATH earlier
    (my:add-to-path
     (my:weak-directory (concat home ".local/bin")))

    ;; add additional paths to PATH as well as exec-path
    (my:add-to-path
     ;; extend the value of EXEC-PATH and $PATH here
     ;; for haskell
     (my:weak-directory (concat home ".ghcup/bin"))
     (my:weak-directory (concat home ".cabal/bin"))
     ;; for rust
     (my:weak-directory (concat home ".cargo/bin")))

    ;; set additional environment variables
    (mapc
     (lambda (kv) (apply #'setenv kv))
     (my:strip-list
      ;; disable guile's auto compilation in REPL
      '("GUILE_AUTO_COMPILE" "0")
      ;; proxy (if you have one)
      '("no_proxy" "localhost,127.0.0.1")
      '("http_proxy" "http://127.0.0.1:2080")
      '("https_proxy" "http://127.0.0.1:2080")
      '("ALL_PROXY" "socks5://127.0.0.1:2080")))
    )
#+end_src

** package manager
As for package configuration, we will use ~use-package.el~, which provides convenient syntactic sugar macros. ~use-package~ is the built-in package management framework for emacs29+ and can get packages from package sources automatically with ~package.el~ with keyword ~:ensure~.

#+begin_src emacs-lisp
  ;; detect native-compile feature
  (when (and (featurep 'native-compile)
             (fboundp 'native-comp-available-p)
             (native-comp-available-p))
    ;; Activate `native-compile'
    (setq native-comp-jit-compilation t
          package-native-compile t))

  ;; pick up a fast ELPA mirror for package.el
  (custom-set-variables
   '(package-archives
     '(;; GNU ELPA (default)
       ;; ("gnu"    . "https://elpa.gnu.org/packages/")
       ;; ("nongnu" . "https://elpa.nongnu.org/nongnu/")
       ;; ("melpa"  . "https://melpa.org/packages/")
       ;; TUNA mirrors (for China Mainland)
       ("gnu"   . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
       ("nongnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/nongnu/")
       ("melpa" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
       ;; ("org" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/org/")
       ))
   )
#+end_src

To accelerate emacs startup we can do:
1. package quickstart. This feature is provided after emacs 27, which supports compile all loaddefs into one single ~package-quickstart.el~ to avoid opening too much loaddef files. This is enabled in [[file:init.el][init.el]].
2. lazy loading. This feature can be enabled automatically by setting ~use-package-deferring-keywords~, all configurations with these keywords present will be deferred by default.

Emacs has a severe performance problem when ~load-path~ is a large list, discussed in Emacs bug#41646 and finally solved by adding a cache-based filter for ~load~ in Emacs 31. Before that, the only way to resolve this problem is to explicitly set file path for ~require~, and the path can only be detected automatically on compilation (otherwise we must code them), this is never implemented in koishimacs, because compilation usually brings more problems.

#+begin_src emacs-lisp
  (use-package use-package
    :preface
    (defvar use-package-selected-packages nil
      "Packages pulled in by use-package.")

    (defvar use-package-vc-selected-packages nil
      "Packages pulled in by use-package-vc.")

    :init
    (define-advice use-package-handler/:ensure
        (:around (fn name keyword args rest state))
      (dolist (ensure args)
        (let ((package
               (or (and (eq ensure t)
                        (use-package-as-symbol name))
                   ensure)))
          (when package
            (when (consp package)
              (setq package (car package)))
            (add-to-list 'use-package-selected-packages package))))
      (funcall fn name keyword args rest state))

    (define-advice use-package-handler/:vc
        (:around (fn name keyword args rest state))
      (add-to-list 'use-package-vc-selected-packages
                   (cons (car args) (cadr args)))
      (add-to-list 'use-package-selected-packages (car args))
      (funcall fn name keyword args rest state))

    (defun my:one-off-hook (hook function &optional depth local)
      "Trigger FUNCTION only once on HOOK, then remove it.
  DEPTH and LOCAL are passed to `add-hook' as optional arguments."
      (let ((fname (gensym "my:one-off-hook-")))
        (eval
         `(add-hook ',hook
                    (defun ,fname ()
                      (,function)
                      (remove-hook ',hook ',fname))
                    ,depth ,local))))

    (defun my:advice-one-off (symbol how function &optional props)
      "Add an one-off advice FUNCTION to SYMBOL, then remove it.
  See description of HOW and PROPS in document of `advice-add'."
      (let ((fname (gensym "my:one-off-advice-")))
        (eval
         `(advice-add ,symbol ,how
                      (defun ,fname ()
                        (,function)
                        (advice-remove ',symbol ',fname))
                      ,props))))

    (defun use-package-handler/:one-off-hook (name _keyword args rest state)
      "Handler for the `:one-off-hook` keyword in `use-package'."
      (use-package-concat
       (use-package-process-keywords name rest state)
       (mapcan
        (lambda (def)
          (let ((syms (car def))
                (fun (cdr def)))
            (when fun
              (mapcar
               (lambda (sym)
                 (let ((symname (symbol-name sym)))
                   (if (and (boundp sym)
                            ;; Mode variables are usually bound, but
                            ;; their hooks are named FOO-mode-hook.
                            (not (string-suffix-p "-mode" symname)))
                       `(my:one-off-hook ',sym #',fun)
                     `(my:one-off-hook
                       ',(intern (concat symname use-package-hook-name-suffix))
                       #',fun))))
               (use-package-hook-handler-normalize-mode-symbols syms)))))
        (use-package-normalize-commands args))))

    (setq use-package-keywords (cons ':one-off-hook use-package-keywords))
    (defalias 'use-package-normalize/:one-off-hook 'use-package-normalize/:hook)
    :custom
    (use-package-always-defer t)
    (use-package-vc-prefer-newest t)
    ;; set up this to get package loading statistics
    (use-package-compute-statistics t)
    )
#+end_src

** hook decorators
Originally I mount a lot of minor modes on ~prog-mode-hook~, however, this may break elisp bytecompile on bootstraping. So I decided to add decorators to such hooks to avoid direct binding to it.

#+begin_src emacs-lisp
  (defvar my/hook-decorators nil
    "A alist of hook decorators, items in (HOOK-NAME . LOADER).")

  (defun my:define-hook-decorator (mode &optional file loader)
    "Define a hook decorator for given name MODE.
  FILE is used for `with-eval-after-load' to ensure MODE is bound, default
  value is MODE.  You may also provide a customized LOADER for loading
  my/MODE-hook."
    (unless (symbolp mode)
      (error "%s is not a symbol!" mode))
    (let ((decorator
           (intern (concat "my/" (symbol-name mode) "-hook")))
          (docstring
           (concat "Hook decorator for `" (symbol-name mode) "'.")))
      ;; define a variable for it using `defvar'
      (eval `(defvar ,decorator nil ,docstring))
      (let ((orig
             (intern (concat (symbol-name mode) "-hook")))
            (file (or file mode)))
        ;; set a loader for that hook decorator
        (setf (alist-get decorator my/hook-decorators)
              (if (and loader (functionp loader))
                  loader
                (lambda ()
                  (with-eval-after-load file
                    (add-to-list orig (lambda () (run-hooks decorator))))))))))

  (defun my:inject-hook-decorators ()
    "Inject hook decorators to those hooks to be decorated."
    (mapc (lambda (decorator) (funcall (cdr decorator)))
          my/hook-decorators))

  (my:define-hook-decorator 'prog-mode)
  (my:define-hook-decorator 'org-mode 'org)

  (add-hook 'after-init-hook #'my:inject-hook-decorators)
#+end_src

** TUI acceleration
We may avoid loading something packages that may cause problems in
terminal. However, the client configuration depends on the daemon. To make
clients available for GUI, the daemon has to be excluded. Unfortunately, we
still can not set this in ~early-init.el~

#+begin_src emacs-lisp
  (defvar my/load-gui-config-p
    (or (display-graphic-p) (daemonp))
    "Indicates whether GUI related config should be loaded.")

  (defvar my/be-iconic-p t
    "Indicates whether use unicode icons.
  Currently we do not have a good way to detect if they're supported.")
#+end_src

** base configuration
Miscellaneous configurations for built-in packages, we should load them earlier so that they can be further tweaked.

#+begin_src emacs-lisp
  ;; fix for archlinux's annoying nested links in mandoc.
  (use-package man
    :config
    (define-advice Man-fontify-manpage (:before ())
      (goto-char (point-min))
      (while (re-search-forward "\x1b\\]8;;.+?\x1b\\\\\\(.+?\\)\x1b]8;;\x1b\\\\" nil t)
        (replace-match "\\1"))
      (goto-char (point-min)))
    )

  (use-package woman
    :config
    (define-advice woman-process-buffer (:before ())
      (goto-char (point-min))
      (while (re-search-forward "\\\\X'tty: link .+?'\\(.+?\\)\\\\X'tty: link'" nil t)
        (replace-match "\\1"))
      (goto-char (point-min)))
    )

  (use-package recentf
    :init
    (recentf-mode)
    :custom
    (recentf-max-saved-items 64)
    ;; do not waste time on checking remote files
    (recentf-keep '(file-remote-p file-readable-p))
    )

  (use-package abbrev :diminish  (abbrev-mode . " "))
  (use-package autorevert :diminish (auto-revert-mode . " "))

  (use-package face-remap
    :diminish (buffer-face-mode . " 󱗌")
    :hook
    (my/prog-mode . buffer-face-mode)
    (my/org-mode . variable-pitch-mode)
    :bind ("C-c v b" . buffer-face-mode)
    )

  (use-package whitespace
    :diminish (whitespace-mode . " ")
    :bind ("C-c v SPC" . whitespace-mode)
    )

  (use-package prog-mode
    :hook
    (my/prog-mode . prettify-symbols-mode)
    (my/prog-mode . display-line-numbers-mode)
    (my/prog-mode
     . (lambda () ;; cleanup whitespaces on save.
         (add-hook 'before-save-hook ;; make it buffer-local
                   #'(lambda () (whitespace-cleanup)) nil t)))
    )

  ;; some general configurations
  (use-package emacs
    :custom
    (blink-cursor-mode nil)
    (buffer-face-mode-face 'default)
    (column-number-mode t)
    (delete-by-moving-to-trash t)
    (fill-column 80)
    (indent-tabs-mode nil)
    (inhibit-startup-screen t)
    (jit-lock-chunk-size 4096)
    (native-comp-async-report-warnings-errors nil)
    (prettify-symbols-unprettify-at-point 'right-edge)
    (scroll-bar-mode nil)
    (size-indication-mode t)
    (tab-always-indent t)
    (tool-bar-mode nil)
    (undo-limit (expt 2 20))
    ;; do not make backups
    (make-backup-files nil)
    ;; or, save backups in a specific directory if necessary
    ;; (backup-directory-alist
    ;;  `(("." . ,(concat user-emacs-directory "backups")))
    :bind
    ([remap list-buffers]    . ibuffer)
    ([remap eval-last-sexp]  . pp-eval-last-sexp)
    ([remap eval-expression] . pp-eval-expression)
    ([remap dabbrev-expand]  . hippie-expand)
    ("C-x M-e" . pp-macroexpand-last-sexp)
    ("C-x M-s" . macrostep-mode)
    ("C-x M-." . xref-find-definitions)
    )

  ;; enable some disabled functions
  (put 'downcase-region 'disabled nil) ;; C-x C-l
  (put 'upcase-region 'disabled nil)   ;; C-x C-u
#+end_src

* UI
** initialization
Setup GUI. We can set the initial X window size and position. It is a pity that the han font can not be scaled once the size is fixed. To solve the problem, we can only set specific font face when width alignment is needed.

#+begin_src emacs-lisp
  (defun my:map-set-fontset-font (&rest arglist)
    "A helper for setup fontsets, ARGLIST is a list of args for `set-fontset-font'."
    (dolist (args arglist)
      (condition-case nil
          (apply #'set-fontset-font args)
        (error (message "failed to apply set-fontset-font to %S" args)))))

  (defun my:map-set-face-attribute (&rest arglist)
    "A helper for run `set-face-attributes' across given ARGLIST."
    (dolist (args arglist)
      (condition-case nil
          (apply #'set-face-attribute args)
        (error (message "failed to apply set-face-attribute to %S" args)))))

  (defun my:setup-fontset ()
    "A subroutine for setting up fontset fonts."
    (my:map-set-fontset-font
     '(t han "LXGW Wenkai Mono")
     '(t kana "LXGW Wenkai Mono")
     '(t nil "Symbols Nerd Font Mono" nil append)
     ))

  (when my/load-gui-config-p
    ;; set fonts
    (my:setup-fontset)
    ;; set faces
    (my:map-set-face-attribute
     '(default nil :family "DejaVu Sans Mono" :slant normal :weight regular :height 128)
     '(fixed-pitch nil :family "DejaVu Sans Mono" :slant normal :weight regular :height 128)
     '(fixed-pitch-serif nil :family "FreeMono" :weight bold :height 136)
     '(variable-pitch nil :family "DejaVu Serif" :height 136)
     )
    ;; set default frame title
    (setq-default frame-title-format
                  (concat "KoishiMACs   👁️   %b   🖌️   " (user-login-name) "@" (system-name)))
    ;; set transparent window for emacs 29+
    (add-to-list 'default-frame-alist '(alpha-background . 80))
    )

  ;; resize initial window when in GUI but not a client
  (when (display-graphic-p)
    ;; set transparent window for emacs 29+
    (set-frame-parameter (selected-frame) 'alpha-background 80)
    ;; (set-frame-position (selected-frame) 60 60)
    (set-frame-size (selected-frame) 100 40)
    )

#+end_src

Setup for server edit: always create a new frame, delete frame when done.

#+begin_src emacs-lisp
  (when (daemonp)
    ;; set fontset for server
    (add-hook 'server-after-make-frame-hook #'my:setup-fontset)

    ;; always create new frame
    (add-hook
     'server-switch-hook
     #'(lambda ()
         (let ((server-buf (current-buffer)))
           (bury-buffer)
           (if server-buffer-clients
               (switch-to-buffer-other-frame server-buf)
             (switch-to-buffer server-buf)))))

    (custom-set-variables '(server-kill-new-buffers t))
    (global-set-key (kbd "C-x C-c") (kbd "C-x # C-x 5 0"))
    ;; resize initial window
    (setf (alist-get 'width default-frame-alist) 100
          (alist-get 'height default-frame-alist) 45
          )
    )
#+end_src

Terminal mode configuration, actually there are very little we can do to the emacsclient. Just assume that clients are all graphic frames.

#+begin_src emacs-lisp
  (unless my/load-gui-config-p
    ;; don't display menu bar
    (menu-bar-mode -1)
    ;; enable mouse navigation if supported
    (xterm-mouse-mode)
    ;; fix arrow keys in some terminals
    (defvar arrow-keys-map (make-sparse-keymap)
      "Keymap for arrow keys.")

    (mapc (lambda (b) (keymap-set arrow-keys-map (car b) (cdr b)))
          '(("A" . [up])
            ("B" . [down])
            ("C" . [right])
            ("D" . [left])))
    ;; arrow keys may be broken in some terminals,
    ;; define a wrapper to translate ESC [ or ESC O
    (keymap-set esc-map "[" arrow-keys-map)
    (keymap-set esc-map "O" arrow-keys-map)
    )
#+end_src

** color scheme
A beautiful color scheme is necessary for everyone's eyes.

#+begin_src emacs-lisp
  (use-package koishi-theme
    :init
    ;; load a sweet color theme
    ;; currently koishi-theme is not suitable for 8-color terminal
    (when (or (daemonp)
              (>= (display-color-cells) 256))
      (load-theme 'koishi))
    ;; background transparency in TUI mode
    (unless my/load-gui-config-p
      (setf (alist-get 'background-color default-frame-alist) nil))
    )
#+end_src

** be iconic.
~diminish~ can replace minor mode lighters in modeline. It has a keyword integration in ~use-package~ but not part of Emacs. However, this package is not part of Emacs, so I decided to re-implement a simple version here.

p. s. but remember that ~diminish.el~ is a nice elisp file to read.
#+begin_src emacs-lisp
  (defvar diminished-mode-alist nil
    "Association list to store diminished (MODE . LIGHTER) .")

  (defun diminish (mode &optional to-what)
    "Replace MODE's modeline lighter to TO-WHAT."
    (when-let* ((minor (assq mode minor-mode-alist)))
      (let ((to-what (or to-what "")))
        (setf (alist-get mode diminished-mode-alist) (cdr minor))
        (setcdr minor (list to-what)))))
#+end_src

** modeline
~doom-modeline~ is the coolest one. However, doom modeline's framework seems to be too heavy for me. So, finally I decided to create a simpler modeline only for koishimacs, named ~violet-line~ for it is colored purple.

#+begin_src emacs-lisp
  ;; violet-line
  (defun violet-line--shrink-path (path &optional max-pixel-width)
    "Return an abbreviation of PATH with respect to MAX-PIXEL-WIDTH."
    (let ((max-pixel-width (or max-pixel-width 600)))
      (if (< (string-pixel-width path) max-pixel-width)
          path
        (let* ((comp (file-name-split path))
               (base (car (last comp)))
               (dirs (mapcan (lambda (s) (unless (string-empty-p s) (list s)))
                             (butlast comp)))
               (shrinked-dirs (mapconcat (lambda (dir)
                                           (substring dir 0 1))
                                         dirs "/"))
               (shrinked-path (concat shrinked-dirs "/" base)))
          (if (< (string-pixel-width shrinked-path) max-pixel-width)
              shrinked-path
            (if (< (string-pixel-width base) max-pixel-width)
                base
              (let* ((space-pixel-width (string-pixel-width " "))
                     (len (floor (/ max-pixel-width space-pixel-width))))
                (if (> len 0)
                    (concat (substring base 0 len) "...")
                  ""))))))))

  (defvar-local violet-line-buffer-icon
      `(:eval
        (when my/be-iconic-p
          (if-let* ((s (buffer-file-name)))
              (nerd-icons-icon-for-file s)
            (nerd-icons-icon-for-buffer))))
    )
  (put 'violet-line-buffer-icon 'risky-local-variable t)

  (defvar-local violet-line-buffer-identification
      `(:eval
        (propertize
         (let ((max-pixel-width
                (- (window-pixel-width)
                   (string-pixel-width
                    (format-mode-line
                     ;; do not cause recursion
                     (delete 'mode-line-format-right-align
                             (remove 'violet-line-buffer-identification
                                     mode-line-format)))))))
           (violet-line--shrink-path
            (if-let* ((s (buffer-file-name)))
                (abbreviate-file-name s)
              (buffer-name))
            max-pixel-width))
         'face 'mode-line-buffer-id
         'help-echo (purecopy "Buffer name\n\
  mouse-1: Previous buffer\n\
  mouse-3: Next buffer")
         'mouse-face 'mode-line-highlight
         'local-map mode-line-buffer-identification-keymap))
    )
  (put 'violet-line-buffer-identification 'risky-local-variable t)

  (defvar-local violet-line-position
      `((:propertize
         ("" mode-line-percent-position)
         local-map ,mode-line-column-line-number-mode-map
         mouse-face mode-line-highlight
         help-echo "Window Scroll Percentage
  mouse-1: Display Line and Column Mode Menu")
        (size-indication-mode
         ,(propertize
           "/%I"
           'local-map mode-line-column-line-number-mode-map
           'mouse-face 'mode-line-highlight
           'help-echo "Size indication mode\n\
  mouse-1: Display Line and Column Mode Menu"))
        ;; column and line number display, leave them unchanged
        ,(assoc 'line-number-mode mode-line-position)
        )
    )
  (put 'violet-line-position 'risky-local-variable t)

  (defface violet-line-emphasis-1
    `((t (:foreground
          ,(if (bound-and-true-p koishi-theme-mode) "#523" "#ADC")
          :weight bold)))
    "A custom face for violet-line segment display.")

  (defvar-local violet-line-modes
      (let ((recursive-edit-help-echo
             "Recursive edit, type C-M-c to get out"))
        (list (propertize "%[" 'help-echo recursive-edit-help-echo)
              `(:propertize ("" mode-name)
                            face violet-line-emphasis-1
                            help-echo "Major mode\n\
  mouse-1: Display major mode menu\n\
  mouse-2: Show help for major mode\n\
  mouse-3: Toggle minor modes"
                            mouse-face mode-line-highlight
                            local-map ,mode-line-major-mode-keymap)
              '("" mode-line-process)
              `(:propertize ("" minor-mode-alist)
                            mouse-face mode-line-highlight
                            help-echo "Minor mode\n\
  mouse-1: Display minor mode menu\n\
  mouse-2: Show help for minor mode\n\
  mouse-3: Toggle minor modes"
                            local-map ,mode-line-minor-mode-keymap)
              (propertize "%n" 'help-echo "mouse-2: Remove narrowing from buffer"
                          'mouse-face 'mode-line-highlight
                          'local-map (make-mode-line-mouse-map
                                      'mouse-2 #'mode-line-widen))
              (propertize "%]" 'help-echo recursive-edit-help-echo)
              " "))
    )
  (put 'violet-line-modes 'risky-local-variable t)

  ;; for right-aligned components
  (setq mode-line-right-align-edge 'right-fringe)

  ;; make use of native mode-line components defined in bindings.el
  (defvar violet-line-format
    `("%e"
      mode-line-front-space
      (:propertize
       (""
        ,mode-line-mule-info
        ,mode-line-client
        ,mode-line-modified
        ,mode-line-remote
        ,mode-line-window-dedicated)
       face mode-line-emphasis
       display (min-width (6.0)))
      mode-line-frame-identification
      violet-line-buffer-icon
      " "
      violet-line-buffer-identification
      "   "
      violet-line-position
      (project-mode-line project-mode-line-format)
      (vc-mode vc-mode)
      mode-line-format-right-align
      "  "
      violet-line-modes
      mode-line-misc-info
      mode-line-end-spaces
      ))
#+end_src

We have a small framework for switching between different mode line styles.

#+begin_src emacs-lisp
  (defvar my/mode-line-styles
    '(standard-mode-line-format
      violet-line-format
      nil)
    "A collection of mode line formats.")

  ;; replace default mode line format
  (setq standard-mode-line-format mode-line-format)
  (setq-default mode-line-format violet-line-format)

  (defun my:set-mode-line-style (name)
    "Switch current `mode-line-format' to NAME.
  With a \\[universal-argument] prefix, set it globally."
    (interactive
     (list (intern (completing-read "Style: " my/mode-line-styles))))
    (eval `(,(if current-prefix-arg 'setq-default 'setq)
            mode-line-format ,name))
    (force-mode-line-update current-prefix-arg))

  (defvar my/saved-mode-line-format violet-line-format)

  (defun my:toggle-mode-line ()
    "Hide or show the mode line in current buffer.
  With a \\[universal-argument] prefix, toggle it globally."
    (interactive)
    (if mode-line-format
        (progn
          (eval `(,(if current-prefix-arg 'setq 'setq-local)
                  my/saved-mode-line-format mode-line-format))
          (my:set-mode-line-style nil))
      (my:set-mode-line-style 'my/saved-mode-line-format)))
  (keymap-global-set "C-c v m" #'my:toggle-mode-line)
#+end_src

** completion
Emacs use minibuffer for quick interactions, most interactions can be accelerated by a powerful completion framework.

#+begin_src emacs-lisp
  (use-package minibuffer
    :custom
    (completion-styles '(basic substring partial-completion flex))
    (completions-detailed t)
    )

  (use-package emacs
    :custom
    (fido-vertical-mode t)
    ;; Enable context menu.
    (context-menu-mode t)
    ;; Support opening new minibuffers from inside existing minibuffers.
    (enable-recursive-minibuffers t)
    ;; Do not allow the cursor in the minibuffer prompt
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt))
    ;; Emacs 28 and newer: Hide commands in M-x which do not work in the current
    ;; mode.
    (read-extended-command-predicate #'command-completion-default-include-p)
    :init
    ;; Add prompt indicator to `completing-read-multiple'.
    ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
    (when (< emacs-major-version 31)
      (define-advice completing-read-multiple
          (:filter-args (args) crm-indicator)
        (cons (format "[CRM%s] %s"
                      (replace-regexp-in-string
                       "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                       crm-separator)
                      (car args))
              (cdr args))))
    :bind
    (:map minibuffer-local-completion-map
          ("S-<up>" . minibuffer-previous-completion)
          ("S-<down>" . minibuffer-next-completion))
    )
#+end_src

** xwidget
~xwidget~ allow us to open webkit windows in Emacs GUI, this is a magnificent work, which nested a modern web browser kit in Emacs. I don't use koishimacs as my desktop and xwidget is not enabled by default, but this really brings a lot of fun.

#+begin_src emacs-lisp
  (use-package xwidget
    :when (and (featurep 'xwidget-internal) my/load-gui-config-p)
    :bind
    (:map xwidget-webkit-edit-mode-map
          ("C-c C-t" . (lambda () (interactive) (xwidget-webkit-edit-mode -1))))
    )
#+end_src

** other widgets
These are my collection, but not that important, or not used.

#+begin_src emacs-lisp
  ;; a sidebar that is never ready for use
  (use-package speedbar
    :custom
    (speedbar-window-default-width 30)
    :custom-face
    (speedbar-button-face ((t :inherit button)))
    (speedbar-directory-face ((t :inherit font-lock-function-name-face)))
    (speedbar-file-face ((t :inherit default)))
    (speedbar-highlight-face ((t :inherit highlight)))
    (speedbar-selected-face ((t :inherit secondary-selection)))
    (speedbar-separator-face ((t :inherit font-lock-punctuation-face)))
    (speedbar-tag-face ((t :inherit font-lock-builtin-face)))
    :config
    (defun my:speedbar-help ()
      (interactive)
      (let ((buf (current-buffer)))
        (other-window 1)
        (describe-bindings nil buf)))
    :bind
    ("C-S-b" . speedbar-window)
    (:map speedbar-mode-map
          ("TAB" . speedbar-toggle-line-expansion)
          ("q" . delete-window)
          ("?" . my:speedbar-help))
    )

#+end_src

** dashboard
A useless thing.

#+begin_src emacs-lisp
  (defun my:dashboard ()
    (interactive)
    (with-current-buffer (get-buffer-create "*Ko-Ko-Da-Yo*")
      (autoload #'org-agenda "org-agenda")
      (autoload #'gnus "gnus")
      (insert
       (propertize
        (with-temp-buffer
          (insert-file-contents
           (my:weak-path (concat user-emacs-directory
                                 "icons/koishimacs-logo.txt")))
          (buffer-string))
        'face 'font-lock-keyword-face))
      (insert "\n\n")
      (insert (propertize (format "GNU Emacs %s started in %s"
                                  emacs-version (emacs-init-time))
                          'face 'font-lock-comment-face))
      (insert "\n\n")
      (insert-button "[  Agenda ]" 'action (lambda (&rest _) (org-agenda-list)))
      (insert "  ")
      (insert-button "[ 󰾱 Gnus ]" 'action (lambda (&rest _) (gnus)))
      (insert "  ")
      (insert-button "[   News ]" 'action (lambda (&rest _) (newsticker-show-news)))
      (insert "  ")
      (insert-button "[   Butterfly ]" 'action (lambda (&rest _) (butterfly)))
      (insert "\n\n")
      (insert (propertize "Rekindled \"The Embers of Love\""
                          'face 'font-lock-doc-face
                          'display '()))
      ;; bind keys
      (keymap-local-set "b" #'butterfly)
      (keymap-local-set "a" #'org-agenda)
      (keymap-local-set "n" #'gnus)
      (keymap-local-set "q" `(lambda () (interactive) (kill-buffer ,(current-buffer))))
      (read-only-mode)
      (switch-to-buffer (current-buffer))))

  (add-hook 'after-init-hook #'my:dashboard)
#+end_src

* Text Editor
** navigation
A hacker can fly across lines and frames.

#+begin_src emacs-lisp
  (use-package windmove
    :init
    (windmove-mode)
    :custom
    (windmove-allow-all-windows t)
    (windmove-default-keybindings '([ignore] meta))
    (windmove-swap-states-default-keybindings '([ignore] meta shift))
    (windmove-wrap-around nil)
    )

  (use-package winner
    :init
    (winner-mode)
    )
#+end_src

** visualization
More previews and visual feedback.

#+begin_src emacs-lisp
  (use-package simple
    :diminish (visual-line-mode . " 󰴐")
    :config
    (when my/load-gui-config-p
      (setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow)))
    :custom
    (word-wrap-by-category t)
    :hook
    (my/org-mode . visual-line-mode)
    :bind
    ("C-c v l" . visual-line-mode)
    )

  (use-package display-fill-column-indicator
    :bind
    ("C-c v i" . display-fill-column-indicator-mode)
    )
#+end_src

** structural edit
Edit text as structural data.

#+begin_src emacs-lisp
  (defun my:kill-ring-save ()
    "Copy region with noselect action -- save current sexp."
    (interactive)
    (unless (region-active-p) (mark-sexp))
    (call-interactively #'kill-ring-save))

  (defun my:kill-region ()
    "Kill region with noselect action -- kill current sexp."
    (interactive)
    (unless (region-active-p) (mark-sexp))
    (call-interactively #'kill-region))

  ;; fold code blocks
  (use-package hideshow
    :diminish (hs-minor-mode . " 󰮕")
    :hook (my/prog-mode . hs-minor-mode)
    )

#+end_src

* Emacs Desktop
** applications
There is a joke that Emacs is actually an operating system shell on lisp.

These applications are actually desktop-level, BTW I use Emacs.

#+begin_src emacs-lisp
  (defun my:sdcv-translate (beg end)
    "Search word at point or words in active region with StarDict."
    (interactive "R")
    (if (region-active-p)
        (shell-command (concat "sdcv -n " (buffer-substring beg end)))
      (shell-command (concat "sdcv -n " (word-at-point t)))))

  (keymap-global-set "M-\"" 'my:sdcv-translate)
#+end_src

* Emacs IDE
** syntax highlights
They are FANTASTIC!!!

#+begin_src emacs-lisp
  (use-package paren
    :custom (show-paren-style 'mixed)
    :custom-face (show-paren-match-expression ((t (:inherit unspecified :background "#554565"))))
    :hook (my/prog-mode . show-paren-mode)
    )
#+end_src

** syntax checker
We got two backends: flycheck and flymake. Flymake is built-in but flycheck is more powerful.

I prefer to use flycheck, but keep a minimal configuration for flymake.
#+begin_src emacs-lisp
  (use-package flyspell
    :diminish (flyspell-mode . " 󰓆")
    :custom
    (flyspell-use-meta-tab nil)
    :bind (:map flyspell-mode-map ("C-;"))
    :hook ((my/org-mode markdown-ts-mode) . flyspell-mode)
    )

  (use-package flymake
    :diminish (flymake-mode . " 󱖊")
    :bind
    (:map flymake-mode-map
          ("C-x ! d" . flymake-show-buffer-diagnostics)
          ("C-x ! D" . flymake-show-project-diagnostics)
          ("C-x ! p" . flymake-goto-prev-error)
          ("C-x ! n" . flymake-goto-next-error))
    )
#+end_src

** code document
Eldoc is the bulitin code document system for emacs, it supports multiple frontends and backends.

#+begin_src emacs-lisp
  (use-package eldoc
    :diminish (eldoc-mode . " 󰙎")
    :init
    (defun my:eldoc-follow-markdown-link ()
      (interactive)
      (when-let* ((url (get-text-property (point) 'help-echo)))
        (eww-browse-url url)))

    (define-advice eldoc--format-doc-buffer
        (:after (&rest r))
      (with-current-buffer eldoc--doc-buffer
        (keymap-local-set "RET" #'my:eldoc-follow-markdown-link)))
    )
#+end_src

** code analysis
Emacs has introduced built-in Language Server Protocol (LSP) support since emacs29, with ~eglot~ package. This package has no extra dependencies, and provides out-of-box lsp client service.

#+begin_src emacs-lisp
  (use-package eglot
    :custom
    (eglot-stay-out-of '(company))
    (eglot-documentation-renderer 'markdown-ts-view-mode)
    :bind
    (:map eglot-mode-map
          ("C-c a" . eglot-code-actions)
          ("C-c =" . eglot-format)
          ("C-c :" . eglot-rename))
    )
#+end_src

Finally we get something cooler in emacs29+, treesit is merged into emacs!

Tree-sitter is a parser generator for creating *incremental* parsers, which provides us many efficient language parsers for syntactic highlighting, code alignment and navigation, etc.

#+begin_src emacs-lisp
  ;; We may enable some built-in treesit modes directly to be lazy
  (use-package treesit
    :custom
    (treesit-font-lock-level 4) ;; as colorful as possible
    (treesit-enabled-modes t)
    :init
    (defvar non-derived-ts-mode-alist
      '((c-mode . c-ts-mode)
        (c++-mode . c++-ts-mode)
        (python-mode . python-ts-mode))
      "A list of (MODE . TS-MODE) for hook transition.")

    ;; append *-mode-hook to *-ts-mode-hook for modes in `major-mode-remap-list'
    (mapc
     #'(lambda (major-mode-remap)
         (let ((major-mode-hook
                (intern (concat (symbol-name (car major-mode-remap)) "-hook")))
               (major-ts-mode-hook
                (intern (concat (symbol-name (cdr major-mode-remap)) "-hook"))))
           (add-hook major-ts-mode-hook
                     `(lambda () (run-hooks ',major-mode-hook)))))
     non-derived-ts-mode-alist)
    )

  ;; c-ts-mode has a rough indentation setting compared to cc-mode
  ;; currently let's add a helper for setting styles
  (use-package c-ts-mode
    :commands (my:c-ts-set-style)
    :config
    (require 'cc-mode)
    (setopt c-guess-region-max 8192)
    (defun my:c-ts-set-style (&optional style)
      "Detect and setup C indentation STYLE for `c-ts-mode'."
      (interactive (list (c-ts-mode--prompt-for-style)))
      ;; detect file mode with cc-mode
      (if style
          (c-ts-mode-set-style style)
        ;; else detect style with `c-guess'
        (progn
          (cond ((eq major-mode 'c-ts-mode) (c-mode))
                ((eq major-mode 'c++-ts-mode) (c++-mode))
                (t (c-or-c++-mode)))
          (condition-case nil
              (c-guess)
            (:success
             (setq-local c-ts-indent-offset c-guess-guessed-basic-offset))
            (error (message "Use default indent=%d" c-ts-indent-offset)))
          (cond ((eq major-mode 'c-mode) (c-ts-mode))
                ((eq major-mode 'c++-mode) (c++-ts-mode)))))
      ;; refresh indent bars
      (when (bound-and-true-p indent-bars-mode)
        (indent-bars-reset)))

    (defun my--c-ts-guess-style ()
      (unless (bound-and-true-p my/c-ts--guessed)
        ;; we must use lexical bindings here, because setq-local is in mode context
        (dlet ((my/c-ts--guessed t))
          (my:c-ts-set-style))))
    :bind
    (:map c-ts-base-mode-map
          ([remap c-ts-mode-set-style] . my:c-ts-set-style))
    :hook
    ((c-ts-mode c++-ts-mode) . my--c-ts-guess-style)
    )

  (use-package lua-ts-mode
    :init
    (defalias 'run-lua 'lua-ts-inferior-lua)
    )

  (use-package markdown-ts-mode
    :commands (markdown-ts-view-mode)
    :mode ("\\.\\(?:md\\|markdown\\|mkd\\|mdown\\|mkdn\\|mdwn\\|mdx\\)\\'" . markdown-ts-mode)
    :bind
    (:map markdown-ts-mode-map
          ("C-c C-x C-l" . org-latex-preview))
    )
#+end_src

** debugger
It is not a fashionable thing to debug in Emacs, most modern IDEs integrates their own debugger. However, that does not mean Emacs is not good at do that. Emacs has GUD (Generic Unified Debugger) as a frontend, which supports many debuggers, especially GDB.

#+begin_src emacs-lisp
  (use-package gud :diminish (gud-mode . " "))
#+end_src

** language-specific supports
Most of them are not configured and deferred.

#+begin_src emacs-lisp
  ;; simple configuration for C/C++ build and debug.
  (use-package emacs
    :hook
    ((c-mode c++-mode)
     . (lambda () ;; one-key C file compilation
         (unless (or (null (buffer-file-name))
                     (file-exists-p "Makefile"))
           (let ((is-c++-p (derived-mode-p 'c++-mode))
                 (file (file-name-nondirectory buffer-file-name)))
             (set (make-local-variable 'compile-command)
                  ;; emulate make's .c.o implicit pattern rule, but with
                  ;; different defaults for the CC, CPPFLAGS, and CFLAGS
                  ;; variables:
                  ;; $(CC) -c -o $@ $(CFLAGS) $<
                  (format "%s -o %s %s %s"
                          (if is-c++-p
                              (or (getenv "CXX") "g++")
                            (or (getenv "CC") "gcc"))
                          (if (file-name-extension file)
                              (file-name-sans-extension file)
                            (concat file ".out"))
                          (if is-c++-p
                              (or (getenv "CPPFLAGS") "-DDEBUG=9")
                            (or (getenv "CFLAGS") "-Wall -g"))
                          file))
             ))
         (keymap-local-set "C-c C-r" #'compile)
         (keymap-local-set "C-c C-d" #'gud-gdb)))
    )

  (use-package inf-lisp
    :init
    (setq inferior-lisp-program "sbcl")
    )

  (use-package lilypond-mode
    :mode ("\\.i?ly\\'" . lilypond-mode)
    :custom
    ;; LilyPond does not support live preview, for live preview,
    ;; run the reader independently if it supports realtime updating.
    (lilypond-ps-command "okular")
    (lilypond-pdf-command "okular")
    )

  (use-package sclang
    :load-path "~/.local/share/SuperCollider/downloaded-quarks/scel/el"
    :mode ("\\.sc\\'" . sclang-mode)
    )
#+end_src

* Org Editor
** gnus
Org will load rmail and gnus when loading modules, so the configuration of these modules must be placed before org.

It is not that fashionable to send and read mails in Emacs, but it just has such a facility.

#+begin_src emacs-lisp
  (use-package message
    :custom
    (message-send-mail-function 'smtpmail-send-it)
    (message-directory
     (my:strong-directory (concat user-emacs-directory "Mail/")))
    )

  (use-package sendmail
    :custom
    (mail-default-directory
     (my:strong-directory (concat user-emacs-directory "sendmail/")))
    (mail-signature-file
     (concat mail-default-directory ".signature"))
    )

  ;; you need to put your mail user authentication information in `auth-source'.
  (use-package smtpmail
    :custom
    (smtpmail-smtp-user "gynamics")
    (smtpmail-smtp-server "mail.coldbench.top")
    (smtpmail-smtp-service 587)
    (smtpmail-stream-type 'starttls)
    (smtpmail-servers-requiring-authorization "mail\\.coldbench\\.top")
    )

  (use-package gnus
    :commands (gnus)
    :custom
    (gnus-home-directory
     (my:strong-directory (concat user-emacs-directory "gnus/")))
    (gnus-directory
     (concat gnus-home-directory "News/"))
    (mail-source-directory message-directory)
    (smime-certificate-directory (concat message-directory "certs/"))
    (user-full-name "gynamics")
    (user-mail-address "gynamics@coldbench.top")
    :config
    (setq gnus-select-method '(nntp "news.gmane.io"))
    (setq gnus-secondary-select-methods
          '((nnimap "coldbench.top"
                    (nnimap-address "mail.coldbench.top")
                    (nnimap-server-port 993)
                    (nnimap-stream tls)
                    (nnimap-inbox "INBOX"))))
    )

  (use-package newsticker
    :init
    (defun my:newsticker-browse-url ()
      (interactive)
      (let ((url))
        (with-current-buffer (newsticker--treeview-list-buffer)
          (setf url (get-text-property (point) :nt-link)))
        (when url (eww-browse-url url))))

    (use-package newst-treeview
      :bind
      (:map newsticker-treeview-item-mode-map
            ("." . my:newsticker-browse-url)))
    :custom-face
    (newsticker-treeview-face ((t (:inherit default :foreground unspecified))))
    :custom
    (newsticker-retrieval-interval 3600)
    (newsticker-retrieval-method 'extern)
    (newsticker-url-list
     '(("LWN (Linux Weekly News)" "https://lwn.net/headlines/rss")
       ("Schneier on Security" "https://www.schneier.com/feed/atom/")
       ("Physics" "https://phys.org/rss-feed/physics-news/physics/")
       ("Astronomy" "https://phys.org/rss-feed/space-news/astronomy/")
       ("Earth" "https://phys.org/rss-feed/earth-news/earth-sciences/")
       ("XKCD" "https://xkcd.com/rss.xml")
       ("Gynamics's Blog Posts" "https://gynamics.top/posts/rss.xml")))
    )
#+end_src

** org-mode
It is really interesting to write ~org-mode~ configurations in an org document.

#+begin_src emacs-lisp
  (use-package org
    :defines org-mode-map
    :init
    (setq org-directory (my:weak-directory "/wsp/doc/org"))

    (defun my:org-agenda-directory ()
      (let ((d1 (file-name-concat org-directory "roam/agenda")))
        (my:strong-directory
         ;; prefer roam subdirectory if available.
         (if (or (featurep 'org-roam-autoloads)
                 (file-directory-p d1))
             d1
           (file-name-concat org-directory "agenda")))))
    (setq my/org-agenda-directory (my:org-agenda-directory)
          org-agenda-files (list my/org-agenda-directory))
    :custom
    (org-default-notes-file (file-name-concat org-directory "notes.org"))
    (org-modules '(ol-doi ol-w3m ol-bbdb ol-bibtex ol-docview ol-gnus ol-info ol-irc ol-mhe ol-rmail ol-eww))
    (org-export-backends '(ascii html latex man md odt texinfo))
    (org-export-with-sub-superscripts nil)
    (org-fontify-inline-src-blocks t)
    (org-fontify-todo-headline t)
    (org-fontify-quote-and-verse-blocks t)
    (org-fontify-whole-block-delimiter-line t)
    (org-fontify-whole-heading-line t)
    (org-format-latex-options '(:foreground default :background "Transparent" :scale 1.0 :html-foreground auto :html-background "Transparent" :html-scale 1.0 :matchers ("begin" "$1" "$" "$$" "\\(" "\\[")))
    (org-hide-emphasis-markers t)
    (org-hide-leading-stars t)
    (org-hide-macro-markers t)
    (org-highlight-latex-and-related '(native latex script entities))
    (org-image-actual-width nil)
    (org-latex-compiler "xelatex")
    (org-latex-src-block-backend 'minted)
    (org-latex-packages-alist
     (append '(("" "color") ("" "minted") ("" "amscd") ("" "amsfonts") ("" "esint"))
             org-latex-default-packages-alist))
    (org-ditaa-jar-path "/usr/share/java/ditaa/ditaa-0.11.jar")
    (org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
    (org-pretty-entities t)
    (org-pretty-entities-include-sub-superscripts nil)
    (org-support-shift-select t)
    (org-src-block-faces 'nil)
    (org-startup-folded 'content)
    (org-startup-with-inline-images my/load-gui-config-p)
    (org-todo-keywords '((sequence "PEND" "TODO" "DONE")))
    (org-todo-keyword-faces '(("PEND" . (:inherit fixed-pitch :foreground "#7FAFF0" :weight bold))))
    (org-use-sub-superscripts nil)
    :custom-face
    (font-latex-math-face ((t (:foreground "burlywood" :box (:line-width (3 . 1) :color "burlywood3")))))
    :config
    ;; xelatex is not very efficient, but tikz only supports pdf output
    ;; original configuration use magick, but dvisvgm actually supports pdf
    (setf
     (alist-get 'xelatex-pdf org-preview-latex-process-alist)
     `(:programs ("xelatex" "dvisvgm") :description "pdf > svg"
       :message "you need to install the programs: xelatex and dvisvgm."
       :image-input-type "pdf" :image-output-type "svg"
       :image-size-adjust (1.7 . 1.5)
       :latex-compiler
       ("xelatex -interaction nonstopmode -output-directory %o %f")
       :image-converter
       (,(concat
          ;; there is a small bug: pdfcrop can not handle empty pdf properly,
          ;; fix it by detecting pdf size with gs and grep, if so, crop it to a small rectangle.
          "if (gs -q -dBATCH -dNOPAUSE -sDEVICE=bbox %f 2>&1 | grep '0 0 0 0');"
          "then pdfcrop --bbox '0 0 5 5' %f %f;"
          "else pdfcrop %f %f;"
          "fi")
        "dvisvgm --pdf --no-fonts --exact --scale=%S %f --output=%O")))

    ;; we use amscd for drawing commutative diagrams now, so tikz is no longer necessary
    ;; since xdv output is faster, use it for default.
    (setq org-preview-latex-default-process 'xelatex)

    ;; This must be deferred after `org-preview-latex-process-alist' is set
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t) (gnuplot . t) (plantuml . t) (dot . t) (shell . t) (latex . t) (lilypond . t)))

    ;; it seems there is an Emacs bug to display transparency.
    ;; in emacs 31, my hotfix patch was not merged, and the display problem was still not solved.
    (when (<= (string-to-number org-version) 9.8)
      (define-advice org--make-preview-overlay
          (:override (beg end image &optional imagetype))
        "Build an overlay between BEG and END using IMAGE file.
     Argument IMAGETYPE is the extension of the displayed image,
     as a string.  It defaults to \"png\"."
        (let ((ov (make-overlay beg end))
              (imagetype (or (intern imagetype) 'png)))
          (overlay-put ov 'org-overlay-type 'org-latex-overlay)
          (overlay-put ov 'evaporate t)
          (overlay-put ov
                       'modification-hooks
                       (list (lambda (o _flag _beg _end &optional _l)
                               (delete-overlay o))))
          (overlay-put ov
                       'display
                       (list 'image :type imagetype :file image :ascent 'center :mask 'heuristic))))
      )

    (defun my:org-toggle-emphasis-markers ()
      "Toggle visibility of emphasis markers in current buffer."
      (interactive)
      (set-variable 'org-hide-emphasis-markers (not org-hide-emphasis-markers))
      (org-restart-font-lock))

    ;; setup faces
    (when my/load-gui-config-p
      (apply
       #'my:map-set-face-attribute
       `((org-document-title nil :weight bold :height 1.5)
         ,@(mapcar
            (lambda (n) `(,(intern (format "org-level-%d" n)) nil
                     :weight bold :height ,(- 1.3 (* n 0.05)) :extend nil))
            (number-sequence 1 5))
         ,@(mapcar
            (lambda (face) `(,face nil :inherit (fixed-pitch)))
            '(org-block org-block-begin-line org-block-end-line org-hide org-meta-line org-property-value org-special-keyword org-table org-todo org-done org-checkbox org-drawer org-footnote org-link))
         ,@(mapcar
            (lambda (face) `(,face nil :inherit (fixed-pitch shadow)))
            '(org-code org-document-info-keyword org-verbatim org-tag))
         )))

    :hook
    (my/org-mode . (lambda () (when my/load-gui-config-p (setq line-spacing 0.1))))
    :bind
    (("C-c a" . org-agenda)
     ("C-c c" . org-capture)
     ("C-c l" . org-store-link)
     :map org-mode-map ;; override keybindings
     ("C-S-<left>"  . windower-move-border-left)
     ("C-S-<right>" . windower-move-border-right)
     ("C-S-<up>"    . windower-move-border-above)
     ("C-S-<down>"  . windower-move-border-below)
     :map org-src-mode-map
     ("C-c C-'" . separedit)
     )
    )

  (use-package org-capture
    :diminish (org-capture-mode . " 󰄀")
    :config
    (defun my:org-capture-agenda-file ()
      (let ((f (file-name-concat my/org-agenda-directory
                                 (format-time-string "agenda-%Y.org"))))
        (unless (file-exists-p f)
          (org-with-file-buffer f
            (goto-char (point-min))
            (org-id-get-create)
            (goto-char (point-max))
            (insert (format-time-string "#+title: Agenda %Y\n"))
            (save-buffer)))
        f))

    (setq org-capture-templates
          '(("t" "Todo" entry (file my:org-capture-agenda-file)
             "* TODO %?\n  %t\n  %a")))
    )

  (use-package org-src
    :config
    (mapc
     (lambda (kv)
       (setf (alist-get (car kv) org-src-lang-modes nil nil #'equal) (cdr kv)))
     '(("python" . python-ts)
       ("scheme" . scheme)
       ("lilypond" . lilypond)
       ("sclang" . sclang)))
    )
#+end_src

** publish
Here is a minimal web publish scaffold. I use ~org-html~ to generate html posts of my essays. I don't want a static site generator, neither a runtime-generated site. It only provides tools for exporting current org file to html in a directory for post.

Resource files are written by myself, not shipped with koishimacs.

#+begin_src emacs-lisp
  (use-package ox
    :commands (my:blog-rsync my:blog-export my:org-blog-post)
    :config
    (defvar my/org-blog-link "https://gynamics.top")
    (defvar my/org-blog-dir "/wsp/edu/gynamics.top/")
    (defvar my/org-blog-post-prefix "posts/")
    (defvar my/org-blog-js-prefix "js/")
    (defvar my/org-blog-rsrc-prefix "resources/")
    (defvar my/org-blog-rss-title "Gynamics' Blog Posts")
    (defvar my/org-blog-rss-desc "Hello, world!")
    (defvar my/org-blog-head
      (format (concat "<div id=\"head-container\">Hello, world!</div>"
                      "<script src=\"%s\"></script>")
              (file-name-concat "/" my/org-blog-js-prefix "head-container.js")))
    (defvar my/org-blog-tail
      (format (concat "<div id=\"tail-container\">&copy %s gynamics</div>"
                      "<script src=\"%s\"></script>")
              (format-time-string "%Y")
              (file-name-concat "/" my/org-blog-js-prefix "tail-container.js")))

    (autoload 'json-read-file "json")
    (defun my:blog-index-update (key &optional title date tags)
      "Update item in index.json with KEY, set its value with TITLE, DATE, TAGS."
      (let* ((f (file-name-concat
                 my/org-blog-dir my/org-blog-post-prefix "index.json"))
             (h (dlet ((json-object-type 'hash-table))
                  (if (file-exists-p f)
                      (json-read-file f)
                    (make-hash-table)))))
        (setf (gethash key h)
              `((title . ,title)
                ;; rfc7321 time format
                (date . ,(format-time-string "%a, %d %b %Y %T %z" date))
                (tags . ,(vconcat tags))))
        (with-temp-file f (json-insert h))))

    (defun my:blog-sitemap-update ()
      "Regenerate sitemap.xml according to index.json."
      (let ((f (file-name-concat
                my/org-blog-dir my/org-blog-post-prefix "index.json")))
        (with-temp-buffer
          (insert "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                  "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">")
          (maphash
           (lambda (k v)
             (insert
              "<url>"
              (format "<loc>%s/%s%s</loc>" my/org-blog-link my/org-blog-post-prefix k)
              (format "<lastmod>%s</lastmod>"
                      ;; iso8061 time format
                      (format-time-string "%F" (encode-time (parse-time-string
                                                             (gethash "date" v)))))
              "</url>\n"))
           (dlet ((json-object-type 'hash-table))
             (if (file-exists-p f)
                 (json-read-file f)
               (make-hash-table))))
          (write-file (file-name-concat my/org-blog-dir "sitemap.xml")))))

    (defun my:blog-sitemap-html-update ()
      "Regenerate static items in sitemap.html according to index.json."
      (let* ((f (file-name-concat
                 my/org-blog-dir my/org-blog-post-prefix "index.json"))
             (data))
        (maphash
         (lambda (k v)
           (push
            (list
             (apply #'encode-time (parse-time-string (gethash "date" v)))
             "<li class=\"item\">"
             (format "<a href=\"%s%s\">%s</a>"
                     my/org-blog-post-prefix k (xml-escape-string (gethash "title" v)))
             (format "<span class=\"tag-list\"> &nbsp; %s &nbsp; </span>"
                     (mapconcat
                      (lambda (tag)
                        (format "<span class=\"tag\" onclick=\"toggleTag('%s')\">#%s</span>"
                                tag tag))
                      (gethash "tags" v)
                      ""))
             (format "<span class=\"timestamp item-date\">%s</span>" (gethash "date" v))
             "</li>\n")
            data))
         (dlet ((json-object-type 'hash-table))
           (if (file-exists-p f)
               (json-read-file f)
             (make-hash-table))))
        (with-temp-buffer
          (insert-file-contents
           (file-name-concat my/org-blog-dir "templates/sitemap.html"))
          (goto-char (point-min))
          (search-forward "<!-- Items -->\n")
          (mapc
           (lambda (l) (apply #'insert (cdr l)))
           (sort data :key #'car :reverse t))
          (write-file (file-name-concat my/org-blog-dir "sitemap.html")))))

    (defun my:blog-rss-update (key title date tags)
      "Update the RSS item with KEY, set its value with TITLE, DATE, TAGS."
      (let ((rss-file (file-name-concat
                       my/org-blog-dir my/org-blog-post-prefix "rss.xml"))
            (rss-link (file-name-concat
                       my/org-blog-link my/org-blog-post-prefix "rss.xml"))
            (link (file-name-concat
                   my/org-blog-link my/org-blog-post-prefix key))
            ;; rfc7321 time format
            (pubdate (format-time-string "%a, %d %b %Y %T %z" date)))
        (let* ((xml
                (if (file-exists-p rss-file)
                    (with-temp-buffer
                      (insert-file-contents rss-file)
                      (libxml-parse-xml-region))
                  `(rss ((version . "2.0")
                         (xmlns:atom . "http://www.w3.org/2005/Atom"))
                        (channel nil
                                 (title nil ,my/org-blog-rss-title)
                                 (link nil ,my/org-blog-link)
                                 (description nil ,my/org-blog-rss-desc)
                                 (atom:link ((href . ,rss-link)
                                             (rel . "self")
                                             (type . "application/rss+xml")))))))
               (channel (car (xml-get-children xml 'channel)))
               (items (xml-get-children channel 'item))
               (new-item `(item nil
                                (title nil ,title)
                                (link nil ,link)
                                (guid ((isPermaLink . "true")) ,link)
                                (pubDate nil ,pubdate)
                                ,@(mapcar (lambda (tag) `(category nil ,tag)) tags))))
          (if-let* ((old-item (seq-find
                              (lambda (item)
                                (when (equal (caddr (car (xml-get-children item 'guid)))
                                             link)
                                  item))
                              items)))
              ;; update
              (setf (cdr old-item) (cdr new-item))
            ;; else insert at tail position
            (nconc channel (list new-item)))
          (with-temp-buffer
            (insert "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
            (xml-print (list xml))
            (write-file rss-file)))))

    (defun my:blog-rsync ()
      (interactive)
      (async-shell-command (concat my/org-blog-dir "rsync-blog.sh")))

    (defun my:blog-export ()
      (interactive)
      (dlet ((org-html-head-include-default-style nil)
             (org-html-head
              (format "<link rel=\"stylesheet\" type=\"text/css\" href=\"%s?v=latest\" />"
                      (file-name-concat "/" my/org-blog-rsrc-prefix "styles.css")))
             (org-html-preamble t)
             (org-html-preamble-format `((,org-export-default-language ,my/org-blog-head)))
             (org-html-postamble t)
             (org-html-postamble-format `((,org-export-default-language ,my/org-blog-tail)))
             (org-html-htmlize-output-type 'css))
        (org-html-export-to-html)))

    (defun my:org-blog-post (&optional sync)
      "Post current Org document to html to `my/org-post-dir'."
      (interactive "P")
      (let ((title (or (org-get-title) "No Title"))
            (org-file (buffer-file-name))
            (f (my:blog-export)))
        (when (file-exists-p f)
          (let ((d (my:strong-directory
                    (file-name-concat my/org-blog-dir my/org-blog-post-prefix)))
                (base (file-name-base f))
                (assets (concat (file-name-sans-extension f) ".assets/")))
            (rename-file f (file-name-concat d (concat base ".html")) t)
            (when (file-directory-p assets)
              (copy-directory assets (file-name-concat d (concat base ".assets/")) t t t))
            (let ((name (concat base ".html"))
                  (date (or (file-attribute-modification-time (file-attributes org-file))
                            (current-time)))
                  (tags (mapcar #'substring-no-properties org-file-tags)))
              (my:blog-index-update name title date tags)
              (my:blog-sitemap-html-update)
              (my:blog-sitemap-update)
              (my:blog-rss-update name title date tags)))))
      (when sync my:blog-rsync))
    )
#+end_src

* Epilogue
** experimental utilities
My own experimental packages, you can get them from github with ~vc-use-package~.
#+begin_src emacs-lisp
  (add-to-list 'load-path (concat user-emacs-directory "site-lisp/"))

  (use-package my-misc
    :defer nil
    :init
    (defalias 'my:asset-directory 'my-misc-asset-directory)
    :bind
    ("M-#"   . my-misc-mark-whole-line)
    ("M-Q"   . my-misc-unfill-paragraph)
    ("C-x %" . my-misc-eval-and-replace)
    ("C-x 9" . my-misc-dedicate-window-toggle)
    ("<f9>"  . my-misc-adjust-alpha-background)
    )

  (use-package oboe
    :commands (oboe-new oboe-recall oboe-absorb oboe-menu oboe-pipe)
    :init
    (defun my:ibuffer-oboe-absorb ()
      "Absorb marked buffers into an oboe buffer."
      (interactive)
      (oboe-absorb (ibuffer-get-marked-buffers)))
    :bind
    ("C-c '" . oboe-blow)
    (:map ibuffer-mode-map :package ibuffer
          ("a" . my:ibuffer-oboe-absorb))
    )

#+end_src

** late configurations
These configurations should be applied later than ~use-package~ configuration blocks.

#+begin_src emacs-lisp
  (unless my/load-gui-config-p
    (setq browse-url-browser-function #'eww-browse-url))

  ;; update list of selected packages
  (setq
   package-selected-packages use-package-selected-packages
   package-vc-selected-packages use-package-vc-selected-packages)
#+end_src

** footer

#+begin_src emacs-lisp
  (provide 'koishimacs)
  ;;; koishimacs.el ends here
#+end_src

** postscript
Nothing.
